CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    telegram_id INTEGER UNIQUE NOT NULL,

    rfid_tag TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mugs (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL DEFAULT "",
    owner_id INTEGER NOT NULL,

    rfid_tag TEXT NOT NULL UNIQUE,

    FOREIGN KEY(owner_id) REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS takenmugs (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    mug_id INTEGER NOT NULL,

    taken_at INTEGER NOT NULL,

    FOREIGN KEY(mug_id) REFERENCES mugs(id)
);
